### ISSUE TITLE
mmseqs

### ISSUE THREAD

**Issue by hooney91** [irycisBioinfo/PATO#4]
Hello

When I run the mmseqs command i got the error

Error in if (grepl("AVX2", system("sysctl -a | grep 'AVX2'", intern = T))) { : 
  argument is of length zero
In addition: Warning message:
In system("sysctl -a | grep 'AVX2'", intern = T) :
  running command 'sysctl -a | grep 'AVX2'' had status 1

The script I used to run it is attached below.

#load gff files
gff_list = dir(path = "./gff", pattern = ".gff", full.names = T)
gff = load_gff_list(gff_list)

#classifier
species = classifier(gff, n_cores = 6, type = "wgs")
species %>% group_by(organism_name) %>% summarise(Number = n())

#MMseq (Many-against-Many sequence searching)
mm = mmseqs(gff, type = "prot")

Thanks

**Comment by valflanza** [comment]
Hello.

What OS are you using? (Windows, Linux, Mac...) and if it is Linux what Distro?

**Comment by hooney91** [comment]
I am using a mac with apple silicon.

**Comment by valflanza** [comment]
Can you try "Sys.getenv("R_PLATFORM")" and tell me what it answer?

**Comment by hooney91** [comment]
The following message is output.
"aarch64-apple-darwin20"

**Comment by hooney91** [comment]
The error was fixed after a recent update.
Thank you.
