### ISSUE TITLE
core_genome

### ISSUE THREAD

**Issue by hooney91** [irycisBioinfo/PATO#5]
When I run the core_gene command i got the error

Error in if (grepl("AVX2", system("sysctl -a | grep 'AVX2'", intern = T))) { : 
  argument is of length zero
In addition: Warning message:
In system("sysctl -a | grep 'AVX2'", intern = T) :
  running command 'sysctl -a | grep 'AVX2'' had status 1

The script I used to run it is attached below.

nr_files = nr_list %>%
  as.data.frame() %>%
  group_by(cluster) %>%
  top_n(1, centrality) %>%
  summarise_all(first) %>%
  select(Source) %>%
  distinct()

core = mmseqs(nr_files) %>% core_genome(type = "prot", n_cores = 6)

Additionally, I am using a mac with apple silicon (aarch64-apple-darwin20).

**Comment by valflanza** [comment]
It is a problem related to the new Apple processors for Mac. We have already solved it. Please update the package.
